background {
    monitor =
    color = rgba(0, 0, 0, 0)
}

animations {
    enabled = false
}

input-field {
    $font = JetBrainsMono Nerd Font
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0)

    outer_color = rgba(ffffffff)
    check_color = rgba(ffffffff)
    fail_color = rgba(255, 0, 0, 1)

    font_color = rgb(255, 255, 255)
    fade_on_empty = false
    rounding = 15

    font_family = $font
    placeholder_text = Password...
    fail_text = Authentication failed

    dots_spacing = 0.3

    position = 0, -20
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME12
    font_size = 90
    font_family = $font

    position = 0, -50
    halign = center
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y" # Update every 60 seconds
    font_size = 25
    font_family = $font

    position = 0, -200
    halign = center
    valign = top
}
