general {
    lock_cmd = pidof hyprlock || hyprlock # Avoid starting multiple hyprlock instances
    before_sleep_cmd = loginctl lock-session # Lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on # Turn on display after wake
}

# Lock screen
listener {
    timeout = 600 # 10 mins
    on-timeout = loginctl lock-session # Lock screen
}

# Turn off screen (DPMS)
listener {
    timeout = 900 # 15 mins
    on-timeout = hyprctl dispatch dpms off # Screen goes black/standby
    on-resume = hyprctl dispatch dpms on # Screen turns back on
}

# Suspend
listener {
    timeout = 1200 # 20 mins
    on-timeout = systemctl suspend # Suspend PC
}
