#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)

exec-once = hyprpaper
exec-once = waypaper --restore
exec-once = waybar
exec-once = swaync
exec-once = systemctl --user start hyprpolkitagent
exec-once = wl-paste --type text --watch cliphist -max-items 20 store
exec-once = wl-paste --type image --watch cliphist -max-items 20 store
exec-once = hypridle